- "3Q": "3Q"
- "AC": "Acer"
- "AZ": "Ainol"
- "AI": "Airness"
- "AL": "Alcatel"
- "A2": "Allview"
- "A1": "Altech UEC"
- "AN": "Arnova"
- "KN": "Amazon"
- "AO": "Amoi"
- "AP": "Apple"
- "AR": "Archos"
- "AS": "ARRIS"
- "AT": "Airties"
- "AU": "Asus"
- "AV": "Avvio"
- "AX": "Audiovox"
- "AY": "Axxion"
- "BB": "BBK"
- "BE": "Becker"
- "BI": "Bird"
- "BL": "Beetel"
- "BM": "Bmobile"
- "BN": "Barnes & Noble"
- "BO": "BangOlufsen"
- "BQ": "BenQ"
- "BS": "BenQ-Siemens"
- "BU": "Blu"
- "BW": "Boway"
- "BX": "bq"
- "BV": "Bravis"
- "BR": "Brondi"
- "B1": "Bush"
- "CB": "CUBOT"
- "CF": "Carrefour"
- "CP": "Captiva"
- "CS": "Casio"
- "CA": "Cat"
- "CE": "Celkon"
- "CC": "ConCorde"
- "C2": "Changhong"
- "CH": "Cherry Mobile"
- "CK": "Cricket"
- "C1": "Crosscall"
- "CL": "Compal"
- "CN": "CnM"
- "CM": "Crius Mea"
- "CR": "CreNova"
- "CT": "Capitel"
- "CQ": "Compaq"
- "CO": "Coolpad"
- "CW": "Cowon"
- "CU": "Cube"
- "CY": "Coby Kyros"
- "DA": "Danew"
- "DT": "Datang"
- "DE": "Denver"
- "DS": "Desay"
- "DB": "Dbtel"
- "DC": "DoCoMo"
- "DI": "Dicam"
- "DL": "Dell"
- "DN": "DNS"
- "DM": "DMM"
- "DO": "Doogee"
- "DV": "Doov"
- "DP": "Dopod"
- "DU": "Dune HD"
- "EB": "E-Boda"
- "EA": "EBEST"
- "EC": "Ericsson"
- "ES": "ECS"
- "EI": "Ezio"
- "EL": "Elephone"
- "EP": "Easypix"
- "E1": "Energy Sistem"
- "ER": "Ericy"
- "EN": "Eton"
- "ET": "eTouch"
- "EV": "Evertek"
- "EX": "Explay"
- "EZ": "Ezze"
- "FA": "Fairphone"
- "FL": "Fly"
- "FO": "Foxconn"
- "FU": "Fujitsu"
- "GM": "Garmin-Asus"
- "GA": "Gateway"
- "GD": "Gemini"
- "GI": "Gionee"
- "GG": "Gigabyte"
- "GS": "Gigaset"
- "GC": "GOCLEVER"
- "GL": "Goly"
- "GO": "Google"
- "GR": "Gradiente"
- "GU": "Grundig"
- "HA": "Haier"
- "HS": "Hasee"
- "HI": "Hisense"
- "HL": "Hi-Level"
- "HO": "Hosin"
- "HP": "HP"
- "HT": "HTC"
- "HU": "Huawei"
- "HX": "Humax"
- "HY": "Hyrican"
- "HN": "Hyundai"
- "IA": "Ikea"
- "IB": "iBall"
- "IJ": "i-Joy"
- "IY": "iBerry"
- "IK": "iKoMo"
- "IM": "i-mate"
- "I1": "iOcean"
- "IW": "iNew"
- "IF": "Infinix"
- "IN": "Innostream"
- "II": "Inkti"
- "IX": "Intex"
- "IO": "i-mobile"
- "IQ": "INQ"
- "IT": "Intek"
- "IV": "Inverto"
- "IZ": "iTel"
- "JI": "Jiayu"
- "JO": "Jolla"
- "KA": "Karbonn"
- "KD": "KDDI"
- "K1": "Kiano"
- "KI": "Kingsun"
- "KO": "Konka"
- "KM": "Komu"
- "KB": "Koobee"
- "KT": "K-Touch"
- "KH": "KT-Tech"
- "KP": "KOPO"
- "KR": "Koridy"
- "KU": "Kumai"
- "KY": "Kyocera"
- "KZ": "Kazam"
- "LV": "Lava"
- "LA": "Lanix"
- "LC": "LCT"
- "LE": "Lenovo"
- "LN": "Lenco"
- "LP": "Le Pan"
- "LG": "LG"
- "LI": "Lingwin"
- "LO": "Loewe"
- "LM": "Logicom"
- "LX": "Lexibook"
- "MJ": "Majestic"
- "MA": "Manta Multimedia"
- "MB": "Mobistel"
- "M3": "Mecer"
- "MD": "Medion"
- "M2": "MEEG"
- "M1": "Meizu"
- "ME": "Metz"
- "MX": "MEU"
- "MI": "MicroMax"
- "MC": "Mediacom"
- "MK": "MediaTek"
- "MO": "Mio"
- "MM": "Mpman"
- "M4": "Modecom"
- "MF": "Mofut"
- "MR": "Motorola"
- "MS": "Microsoft"
- "MZ": "MSI"
- "MU": "Memup"
- "MT": "Mitsubishi"
- "ML": "MLLED"
- "MQ": "M.T.T."
- "MY": "MyPhone"
- "NE": "NEC"
- "NA": "Netgear"
- "NG": "NGM"
- "NI": "Nintendo"
- "N1": "Noain"
- "NK": "Nokia"
- "NM": "Nomi"
- "NN": "Nikon"
- "NW": "Newgen"
- "NX": "Nexian"
- "NT": "NextBook"
- "OD": "Onda"
- "ON": "OnePlus"
- "OP": "OPPO"
- "OR": "Orange"
- "OT": "O2"
- "OK": "Ouki"
- "OU": "OUYA"
- "OO": "Opsson"
- "PA": "Panasonic"
- "PE": "PEAQ"
- "PG": "Pentagram"
- "PH": "Philips"
- "PI": "Pioneer"
- "PL": "Polaroid"
- "PM": "Palm"
- "PO": "phoneOne"
- "PT": "Pantech"
- "PY": "Ployer"
- "PV": "Point of View"
- "PP": "PolyPad"
- "P2": "Pomp"
- "PS": "Positivo"
- "PR": "Prestigio"
- "P1": "ProScan"
- "PU": "PULID"
- "QI": "Qilive"
- "QT": "Qtek"
- "QM": "QMobile"
- "QU": "Quechua"
- "OV": "Overmax"
- "OY": "Oysters"
- "RA": "Ramos"
- "RC": "RCA Tablets"
- "RB": "Readboy"
- "RI": "Rikomagic"
- "RM": "RIM"
- "RK": "Roku"
- "RO": "Rover"
- "SA": "Samsung"
- "SD": "Sega"
- "SE": "Sony Ericsson"
- "S1": "Sencor"
- "SF": "Softbank"
- "SX": "SFR"
- "SG": "Sagem"
- "SH": "Sharp"
- "SI": "Siemens"
- "SN": "Sendo"
- "SK": "Skyworth"
- "SC": "Smartfren"
- "SO": "Sony"
- "SP": "Spice"
- "SU": "SuperSonic"
- "SV": "Selevision"
- "SY": "Sanyo"
- "SM": "Symphony"
- "SR": "Smart"
- "S4": "Star"
- "ST": "Storex"
- "S2": "Stonex"
- "S3": "SunVan"
- "SZ": "Sumvision"
- "TA": "Tesla"
- "T5": "TB Touch"
- "TC": "TCL"
- "TE": "Telit"
- "T4": "ThL"
- "TH": "TiPhone"
- "TB": "Tecno Mobile"
- "TD": "Tesco"
- "TI": "TIANYU"
- "TL": "Telefunken"
- "T2": "Telenor"
- "TM": "T-Mobile"
- "TN": "Thomson"
- "T1": "Tolino"
- "TO": "Toplux"
- "TS": "Toshiba"
- "TT": "TechnoTrend"
- "T3": "Trevi"
- "TU": "Tunisie Telecom"
- "TR": "Turbo-X"
- "TV": "TVC"
- "TX": "TechniSat"
- "TZ": "teXet"
- "UN": "Unowhy"
- "US": "Uniscope"
- "UT": "UTStarcom"
- "VA": "Vastking"
- "VD": "Videocon"
- "VE": "Vertu"
- "VI": "Vitelcom"
- "VK": "VK Mobile"
- "VS": "ViewSonic"
- "VT": "Vestel"
- "VV": "Vivo"
- "V1": "Voto"
- "VO": "Voxtel"
- "VF": "Vodafone"
- "VZ": "Vizio"
- "VW": "Videoweb"
- "WA": "Walton"
- "WE": "WellcoM"
- "WY": "Wexler"
- "WI": "Wiko"
- "WL": "Wolder"
- "WO": "Wonu"
- "WX": "Woxter"
- "XI": "Xiaomi"
- "XO": "Xolo"
- "YA": "Yarvik"
- "YU": "Yuandao"
- "YS": "Yusun"
- "YT": "Ytone"
- "ZE": "Zeemi"
- "ZO": "Zonda"
- "ZP": "Zopo"
- "ZT": "ZTE"
- "WB": "Web TV"
- "XX": "Unknown"
